<?php

namespace App\Enums;

use Spatie\Enum\Laravel\Enum;

/**
 * @method static self add()
 * @method static self sub()
 */
final class TransactionType extends Enum
{
    public static function values(): array
    {
        return [
            'add' => '+',
            'sub' => '-',
        ]; // TODO: Change the autogenerated stub
    }
}
