# Default values for laravel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/mhadiahmed/fortore_investment
  pullPolicy: Always
  tag: "stable"
release_hash: "23sdafsdflkjskldf"
imagePullSecrets:
  - name: registry-github-com-docker-registry-token
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80


storage:
  enabled: true
  size: 50Gi



ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/protocol: https
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
  hosts:
    - host: fortoremallloyalty.com
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - hosts:
        - fortoremallloyalty.com
      secretName: fortoremallloyalty-com-crt

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  volumePermissions:
    enabled: true
  auth:
    database: "app"
    rootPassword: "app"

env:
  - name: APP_DEBUG
    value: "false"
  - name: MAIL_MAILER
    value: "log"
  - name: APP_NAME
    value: "laravel"
  - name: APP_URL
    value: "https://fortoremallloyalty.com"
  - name: APP_ENV
    value: "production"
